spring:
  application:
    name: ai-coder
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.35.203:13306/ai-coder
    username: root
    password: 3r2ZShXsDNY5Nhkk
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-aicoder
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ruizhou.aicoder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

